### ISSUE TITLE
Mixin applying failed for lithium

### ISSUE THREAD

**Issue by SettingDust** [Snownee/Loquat#2]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

1.2.3

### Modloader version

0.14.22

### Modpack info

https://modrinth.com/modpack/fabulously-optimized

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://mclo.gs/om2oqvk

### Issue description

```
[09:15:32] [Server thread/ERROR] (Minecraft) Couldn't place player in world
java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.lithium.common.entity.LithiumEntityCollisions failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.22.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.world.World.isSpaceEmpty(World.java:9064) ~[client-intermediary.jar:?]
	at net.minecraft.world.CollisionView.isSpaceEmpty(CollisionView.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.server.network.ServerPlayerEntity.moveToSpawn(ServerPlayerEntity.java:296) ~[client-intermediary.jar:?]
	at net.minecraft.server.network.ServerPlayerEntity.<init>(ServerPlayerEntity.java:264) ~[client-intermediary.jar:?]
	at net.minecraft.server.PlayerManager.createPlayer(PlayerManager.java:461) ~[client-intermediary.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler.java:133) ~[client-intermediary.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$ejo000$fabric-networking-api-v1$handlePlayerJoin(ServerLoginNetworkHandler.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection.java:248) ~[client-intermediary.jar:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:183) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:886) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bei000$carpet$modifiedRunLoop(MinecraftServer.java:4885) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method loquat$getEntityWorldBorderCollisions(Lnet/minecraft/world/World;Lnet/minecraft/entity/Entity;Lnet/minecraft/util/math/Box;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/util/ArrayList;)V in loquat.mixins.json:lithium.LithiumEntityCollisionsMixin from mod loquat failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap loquat.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.22.jar:?]
	... 21 more
```

**Comment by SettingDust** [comment]
Reproduce with only 6. Conflicting with memory leak fix
![图片](https://github.com/Snownee/Loquat/assets/19922286/b7a61070-c091-4e11-a3ee-2a5e9e773e06)

**Comment by Snownee** [comment]
Unrelated to Memory Leak Fix. This is my setup and it failed too.
![image](https://github.com/Snownee/Loquat/assets/16059084/1bb85cfb-dcfc-4416-8499-93ce905fa8b1)
No clue why though...

**Comment by SettingDust** [comment]
But it's not crash without memory leak fix with only the 5 mods
![@4A`4KFY%4KK2ZXM{ Q5L_9](https://github.com/Snownee/Loquat/assets/19922286/886bcdc7-c2d3-41c4-ae8b-882e3141b47c)

**Comment by SettingDust** [comment]
Forget that it's happened on entering world. Not related to Memory Leak Fix
